
["The Bumblezone Dimension Options"]
	# 
	#-----------------------------------------------------
	#
	# How bright the fog is in the Bumblezone dimension. 
	# 
	# The brightness is represented as a percentage
	# so 0 will be pitch black, 50 will be half
	# as bright, 100 will be normal orange brightness,
	# and 100000 will be white.
	#
	#Range: 0.0 ~ 100000.0
	fogBrightnessPercentage = 100.0
	# 
	#-----------------------------------------------------
	#
	# How much to reduce the thickness of the fog in Bumblezone. 
	# 1 is for Nether fog thickness. 10 for much farther fog.
	#
	#Range: 0.0 ~ 100.0
	fogReducer = 4.0
	# 
	#-----------------------------------------------------
	#
	# Whether Bumblezone dimension has thick fog or not.
	#
	enableDimensionFog = true

["The Bumblezone Teleportation Options"]
	# 
	#-----------------------------------------------------
	#
	# Which mode of teleportation should be used when 
	# leaving The Bumblezone dimension. 
	# 
	# Mode 1: Coordinates will be converted to the other 
	# dimension's coordinate scale and the game will look for
	# a Bee Nest/Beehive at the new spot to spawn players at. 
	# If none is found, players will still be placed at the spot.
	# 
	# Mode 2: Will always spawn players at the original spot in the
	# non-BZ dimension where they threw the Enderpearl at a Bee Nest/Beehive.
	# Coordinate scale of dimension is ignored both ways.
	# 
	#Mode 3: Will use mode 1's teleportation method if Bee Nest/Beehive
	#is near the spot when exiting the dimension. If none is found,
	#then mode 2's teleportation method is used instead.
	#
	#Range: 1 ~ 3
	teleportationMode = 3
	# 
	#-----------------------------------------------------
	#
	# Allow Bumblezone mod to handle teleporting into the Bumblezone dimension.
	#
	enableEntranceTeleportation = true
	# 
	#-----------------------------------------------------
	#
	# Allow Bumblezone mod to handle teleporting out of the Bumblezone dimension.
	#
	enableExitTeleportation = true
	# 
	#-----------------------------------------------------
	#
	# If this is enabled, mobs that originally spawned in Bumblezone will be teleported
	# to 0, 0 center of the Overworld when exiting Bumblezone dimension.
	#
	forceBumblezoneOriginMobToOverworldCenter = true
	# 
	#-----------------------------------------------------
	#
	# Will a Beenest generate if no Beenest is  
	# found when leaving The Bumblezone dimension.
	# 
	# ONLY FOR TELEPORTATION MODE 1.
	#
	generateBeenest = true
	# 
	#-----------------------------------------------------
	#
	# Makes leaving The Bumblezone dimension always places you back
	# at the Overworld regardless of which dimension you originally 
	# came from. Use this option if this dimension becomes locked in  
	# with another dimension so you are stuck teleporting between the 
	# two and cannot get back to the Overworld.
	#
	forceExitToOverworld = false
	# 
	#-----------------------------------------------------
	#
	# Makes throwing Enderpearls at Bee Nests or Hives only 
	# work in the Overworld. What this means setting this to true makes it 
	# only possible to enter The Bumblezone dimension from the Overworld
	onlyOverworldHivesTeleports = false
	# 
	#-----------------------------------------------------
	#
	# Should exiting The Bumblezone always try and place you 
	# above sealevel in the target dimension? (Will only look 
	# for beehives above sealevel as well when placing you)
	# 
	# ONLY FOR TELEPORTATION MODE 1 AND 3.
	#
	seaLevelOrHigherExitTeleporting = true
	# 
	#-----------------------------------------------------
	#
	# If the block tag file required_block_under_hive.json has blocks specified 
	# and this config is set to true, then player will get a warning if they
	# throw an Enderpearl at a Bee Nest/Beehive but the block under it is 
	# not the correct required block. It will also tell the player what 
	# block is needed under the Bee Nest/Beehive to teleport to the dimension.
	#
	warnPlayersOfWrongBlockUnderHive = true
	# 
	#-----------------------------------------------------
	#
	# Should teleporting to and from The Bumblezone work 
	# with modded Bee Nests and modded Beehives as well. 
	#
	allowTeleportationWithModdedBeehives = true
	# 
	#-----------------------------------------------------
	#
	# Changes the default dimension that teleporting exiting will take mobs to 
	# if there is no previously saved dimension on the mob. 
	# Use this option ONLY if your modpack's default dimension is not the Overworld. 
	# This will affect forceExitToOverworld, forceBumblezoneOriginMobToOverworldCenter, and onlyOverworldHivesTeleports
	# config options so that they use this new default dimension instead of overworld.
	#
	defaultDimension = "minecraft:overworld"

