
["Beehemoth Options"]
	# 
	#-----------------------------------------------------
	#
	# Base speed for the Beehemoth when being rode by a player.
	#
	#Range: 0.0 ~ 100.0
	beehemothSpeed = 0.95

["Special Bee Spawning Options"]
	# 
	#-----------------------------------------------------
	#
	# Whether Bumblezone will handle spawning vanilla bees near players in the Bumblezone to make it feel full of Bees.
	# Bees too far will be despawned in Bumblezone unless the bee has a hive, is name tagged, or is set to persistent.
	# Note: Modded bees will not be spawned through this system. Those will be spawned by normal biome spawning.
	#
	specialBeeSpawning = true
	# 
	#-----------------------------------------------------
	#
	# If specialBeeSpawning is set to true, this config controls how many vanilla bees should be
	# near each player in Bumblezone dimension. Higher numbers like 100 is insane lol. 25 is nice.
	#
	#Range: 0 ~ 1000
	nearbyBeesPerPlayerInBz = 25

["General Mechanics Options"]
	# 
	#-----------------------------------------------------
	#
	# Should Dispensers always drop the Glass Bottle when using specific 
	# bottle items on certain The Bumblezone blocks? 
	# 
	# Example: Using Honey Bottle to feed Honeycomb Brood Blocks will grow the larva and
	# drop the Glass Bottle instead of putting it back into Dispenser if this is set to true.
	#
	dispensersDropGlassBottles = false
	# 
	#-----------------------------------------------------
	#
	# How long in seconds this music disc will be playing music.
	# This is used for the server to know when to make Allays stop dancing when Jukebox plays this music disc.
	#
	#Range: 0 ~ 1000000
	broodBlocksBeeSpawnCapacity = 84
	# 
	#-----------------------------------------------------
	#
	# How long in seconds this music disc will be playing music.
	# This is used for the server to know when to make Allays stop dancing when Jukebox plays this music disc.
	#
	#Range: 0 ~ 1000000
	musicDiscTimeLengthHoneyBee = 216
	# 
	#-----------------------------------------------------
	#
	# Whether Essence of the Bees's effect should stay on the player if they die and then respawn.
	#
	keepEssenceOfTheBeesOnRespawning = true
	# 
	#-----------------------------------------------------
	#
	# Whether the Crystalline Flower block will eat any item entity that touches the block's collision box in the world
	#
	crystallineFlowerConsumeItemEntities = true
	# 
	#-----------------------------------------------------
	#
	# Whether the Crystalline Flower block will pull in and eat any experience orb that touches it in the world
	#
	crystallineFlowerConsumeExperienceOrbEntities = true
	# 
	#-----------------------------------------------------
	#
	# Whether the Crystalline Flower's GUI allows players to feed it items directly
	#
	crystallineFlowerConsumeItemUI = true
	# 
	#-----------------------------------------------------
	#
	# Whether the Crystalline Flower's GUI allows players to feed it the player's experience
	#
	crystallineFlowerConsumeExperienceUI = true
	# 
	#-----------------------------------------------------
	#
	# Controls how much "enchanting power" is used per tier to determine what enchantment shows up.
	# Enchantments of higher levels or rarity requires more "enchanting power" before they show up in the UI.
	# Think of this like how Enchanting Tables only shows stronger or rarer enchantments when you have more bookshelves.
	# Except here, the flower's tier times this config value is used as the threshold to know what enchantment and level to show.
	#
	#Range: 0 ~ 1000
	crystallineFlowerEnchantingPowerAllowedPerTier = 8
	# 
	#-----------------------------------------------------
	#
	# How much extra experience is required to reach the next tier for the Crystalline Flower.
	# Remember, item consuming is also affected as items are converted to experience when the flower consumes it.
	#
	#Range: -1000000 ~ 1000000
	crystallineFlowerExtraXpNeededForTiers = 0
	# 
	#-----------------------------------------------------
	#
	# Increases or decreases the tier cost of all enchantments available by whatever value you set.
	# The enchantment's tier cost will be capped between 1 and 6.
	#
	#Range: -5 ~ 5
	crystallineFlowerExtraTierCost = 0
	# 
	#-----------------------------------------------------
	#
	# How long in seconds this music disc will be playing music.
	# This is used for the server to know when to make Allays stop dancing when Jukebox plays this music disc.
	#
	#Range: 0 ~ 1000000
	musicDiscTimeLengthBeeLaxingWithTheHomBees = 300
	# 
	#-----------------------------------------------------
	#
	# How long in seconds this music disc will be playing music.
	# This is used for the server to know when to make Allays stop dancing when Jukebox plays this music disc.
	#
	#Range: 0 ~ 1000000
	musicDiscTimeLengthLaBeeDaLoca = 176
	# 
	#-----------------------------------------------------
	#
	# Allows lit Super Candles/Incense Candle to burn mobs in its flame.
	#
	superCandlesBurnsMobs = true
	# 
	#-----------------------------------------------------
	#
	# Multiplies the trade reward by this much for bonus Trades! 0 or 1 set here disables bonus Trades.
	#
	#Range: 0 ~ 256
	beeQueenBonusTradeRewardMultiplier = 3
	# 
	#-----------------------------------------------------
	#
	# How long in ticks that bonus Trades will last for before the Bee Queen asks for a new item.
	# Setting this to 0 disables bonus Trades. Anything less than a minute (1200) will not broadcast request message to players
	#
	#Range: 0 ~ 2000000
	beeQueenBonusTradeDurationInTicks = 24000
	# 
	#-----------------------------------------------------
	#
	# How many boosted trades are allowed until the bonus Trade is depleted until the queen requests a new item
	# Setting this to 0 disables bonus Trades.
	#
	#Range: 0 ~ 1000000
	beeQueenBonusTradeAmountTillSatified = 24

["Bee Loot Injection Options"]
	# 
	#-----------------------------------------------------
	#
	# Whether Bee Stingers should drop from adult Bees that die while still having their stinger.
	# This pulls from this loot table for the drops: `the_bumblezone:entities/bee_stinger_drops`
	#
	beeLootInjection = true
	# 
	#-----------------------------------------------------
	#
	# Whether Bee Stingers should drop from adult modded Bees that die while still having their stinger.
	# This pulls from this loot table for the drops: `the_bumblezone:entities/bee_stinger_drops`
	#
	moddedBeeLootInjection = true

