
["Mod Compatibility Options"]

	["Mod Compatibility Options"."General Compat Options"]
		# 
		#-----------------------------------------------------
		#
		# Will let you feed any item that has a Forge fluid capability attached and has 
		#  any fluid that is tagged forge:fluid/honey inside. This works alongside the bee_feeding item tag.
		#  An item can still be fed even if bee_feeding tag doesn't have the item as long as the 
		# item fit the above conditions with the fluid capability and this config is set to true.
		#
		allowHoneyFluidTanksFeedingCompat = true

	["Mod Compatibility Options"."Pokecube Options"]
		# 
		#-----------------------------------------------------
		#
		# Spawn Pokecube's bee-like pokemon in The Bumblezone and from Honey Brood Blocks.
		#
		spawnPokecubeBeePokemon = true
		# 
		#-----------------------------------------------------
		#
		# Chance of a Bee spawning from Honeycomb Brood Blocks being replaced by Pokecube's bee pokemon.
		# 0 is no PC's mobs and 1 is max PC's mobs.
		#
		#Range: 0.0 ~ 1.0
		spawnrateOfPokecubeBeePokemon = 0.02
		# 
		#-----------------------------------------------------
		#
		# Pokecube's bee-like pokemon that spawn in The Bumblezone will get
		# Protection of the Hive effect. Attacking these pokemon in bumblezone will
		# give you Wrath of the Hive effect and swarmed of angry bees.
		#
		beePokemonGetsProtectionEffect = true

	["Mod Compatibility Options"."Productive Bees Options"]
		# 
		#-----------------------------------------------------
		#
		# Spawn Productive Bees in The Bumblezone and from Honey Brood Blocks alongside
		# regular bees at a spawnrateOfProductiveBeesMobs chance when spawning regular bees.
		#
		spawnProductiveBeesBeesMob = true
		# 
		#-----------------------------------------------------
		#
		# Chance of a Bee spawning in Bumblezone or from Honeycomb Brood Blocks being replaced by Productive Bee's mob.
		# 0 is no PB's mobs and 1 is max PB's mobs.
		#
		#Range: 0.0 ~ 1.0
		spawnrateOfProductiveBeesMobs = 0.03
		# 
		#-----------------------------------------------------
		#
		# Spawn Productive Bees's various honeycomb variants in The Bumblezone at all
		# kinds of heights and height bands. Start exploring to find where they spawn!
		# 
		# NOTE: Will require a restart of the world to take effect. 
		#
		spawnProductiveBeesHoneycombVariants = true
		# 
		#-----------------------------------------------------
		#
		# Allow what Productive Bees combs should be able to spawn in Bumblezone dungeons.
		allowedCombsForDungeons = ["productivebees:diamond", "productivebees:iron", "productivebees:coal", "productivebees:redstone", "productivebees:copper", "productivebees:lapis", "productivebees:gold", "productivebees:emerald", "productivebees:obsidian", "productivebees:experience", "productivebees:magmatic", "productivebees:amethyst", "productivebees:prismarine", "productivebees:crystalline", "productivebees:sugarbag", "productivebees:glowing", "productivebees:frosty", "productivebees:slimy", "productivebees:silky", "productivebees:blazing", "productivebees:ender", "productivebees:skeletal", "productivebees:ghostly", "productivebees:zombie"]
		# 
		#-----------------------------------------------------
		#
		# Allow what Productive Bees combs should be able to spawn in Bumblezone as ores.
		allowedCombsAsOres = ["productivebees:iron", "productivebees:redstone", "productivebees:copper", "productivebees:gold", "productivebees:magmatic", "productivebees:crystalline", "productivebees:glowing", "productivebees:blazing", "productivebees:skeletal", "productivebees:ghostly"]
		# 
		#-----------------------------------------------------
		#
		# Allow what Productive Bees bees should be able to spawn in Bumblezone. 
		blacklistedBees = ["productivebees:diamond", "productivebees:iron", "productivebees:coal", "productivebees:redstone", "productivebees:copper", "productivebees:lapis", "productivebees:gold", "productivebees:emerald", "productivebees:obsidian", "productivebees:experience", "productivebees:magmatic", "productivebees:amethyst", "productivebees:prismarine", "productivebees:crystalline", "productivebees:sugarbag", "productivebees:glowing", "productivebees:frosty", "productivebees:slimy", "productivebees:silky", "productivebees:blazing", "productivebees:ender", "productivebees:skeletal", "productivebees:ghostly", "productivebees:zombie"]
		# 
		#-----------------------------------------------------
		#
		# Allow Honey Treat to be able to feed bees and Honeycomb Brood Blocks.
		#
		allowHoneyTreatCompat = true
		# 
		#-----------------------------------------------------
		#
		# How much of Bee Dungeons is made of ore-based honeycombs.
		# 0 is no PB's honeycombs and 1 is max PB's honeycombs.
		#
		#Range: 0.0 ~ 1.0
		PBOreHoneycombSpawnRateBeeDungeon = 0.06
		# 
		#-----------------------------------------------------
		#
		# How much of Spider Infested Bee Dungeons is made of ore-based honeycombs.
		# 0 is no PB's honeycombs and 1 is max PB's honeycombs.
		#
		#Range: 0.0 ~ 1.0
		PBOreHoneycombSpawnRateSpiderBeeDungeon = 0.12

	["Mod Compatibility Options"."Friends and Foes Options"]
		# 
		#-----------------------------------------------------
		#
		# Adds Bumblezone items to Friends and Foes's Beekeeper trades!
		#
		allowFriendsAndFoesBeekeeperTradesCompat = true

	["Mod Compatibility Options"."Quark Options"]
		# 
		#-----------------------------------------------------
		#
		# Adds Bumblezone items symbols to Quark's enchantment tooltips!
		#
		injectBzItemsIntoQuarkEnchantmentTooltipsCompat = true

	["Mod Compatibility Options"."Buzzier Bees Options"]
		# 
		#-----------------------------------------------------
		#
		# Allow Bee Bottle to turn Empty Honeycomb Brood blocks into 
		# a regular Honeycomb Brood Block with a larva inside! 
		#
		allowBeeBottleRevivingEmptyBroodBlock = true
		# 
		#-----------------------------------------------------
		#
		# Allow Buzzier Bees's Crystallized honey block to spawn in patches on surfaces in Bumblezone Dimension. 
		# Requires a game restart to take effect (close game and re-open) 
		#
		spawnCrystallizedHoneyInDimension = true
		# 
		#-----------------------------------------------------
		#
		# Allow Buzzier Bees's Honey Tile block to spawn mainly in caves inside Bumblezone Dimension. 
		# Requires a game restart to take effect (close game and re-open) 
		#
		spawnHoneyTilesInDimension = true

	["Mod Compatibility Options"."Resourceful Bees Options"]
		# 
		#-----------------------------------------------------
		#
		# Spawn Resourceful Bees in The Bumblezone and from Honey Brood Blocks alongside
		# regular bees at a spawnrateOfResourcefulBeesMobs chance when spawning regular bees.
		# You can datapack the_bumblezone:resourcefulbees/spawnable_from_brood_block entity tag
		# and/or datapack the_bumblezone:resourcefulbees/spawnable_from_chunk_creation entity tag
		# for more control of what kinds of bees spawns.
		#
		spawnResourcefulBeesBeesMob = true
		# 
		#-----------------------------------------------------
		#
		# Chance of a Bee spawning from Honeycomb Brood Blocks in Bumblezone dimension being replaced by Resourceful Bee's mob.
		# 0 is no RB's mobs and 1 is max EB's mobs.
		#
		#Range: 0.0 ~ 1.0
		spawnrateOfResourcefulBeesMobsBrood = 0.03
		# 
		#-----------------------------------------------------
		#
		# Chance of a regular Bee spawning in Bumblezone being replaced by Resourceful Bee's mob.
		# 0 is no RB's mobs and 1 is max RB's mobs.
		#
		#Range: 0.0 ~ 1.0
		spawnrateOfResourcefulBeesMobsOther = 0.008
		# 
		#-----------------------------------------------------
		#
		# How much of Bee Dungeons is made of honeycombs from the_bumblezone:resourcefulbees/spawns_in_bee_dungeons block tag.
		# 0 is no RB's honeycombs and 1 is max RB's honeycombs.
		#
		#Range: 0.0 ~ 1.0
		RBOreHoneycombSpawnRateBeeDungeon = 0.06
		# 
		#-----------------------------------------------------
		#
		# How much of Spider Infested Bee Dungeons is made of honeycombs from the_bumblezone:resourcefulbees/spawns_in_spider_infested_bee_dungeons block tag.
		# 0 is no RB's honeycombs and 1 is max RB's honeycombs.
		#
		#Range: 0.0 ~ 1.0
		RBOreHoneycombSpawnRateSpiderBeeDungeon = 0.12
		# 
		#-----------------------------------------------------
		#
		# Spawn Resourceful Bees's various honeycomb variants in The Bumblezone at all
		# kinds of heights and height bands. Start exploring to find where they spawn!
		# 
		# NOTE: Will require a restart of the world to take effect. 
		#
		spawnResourcefulBeesHoneycombVeins = true

	["Mod Compatibility Options"."Potion of Bees Options"]
		# 
		#-----------------------------------------------------
		#
		# Allow Potion of Bees to turn Empty Honeycomb Brood blocks into 
		# a regular Honeycomb Brood Block with a larva inside! 
		#
		allowPotionOfBeesRevivingEmptyBroodBlock = true

