
#Common Settings
[common]
	#Disable / enable any items here (disables their recipes)
	enabledItems = [
		"sophisticatedbackpacks:anvil_upgrade|true",
		"sophisticatedbackpacks:battery_upgrade|false",
		"sophisticatedbackpacks:compacting_upgrade|true",
		"sophisticatedbackpacks:advanced_compacting_upgrade|true",
		"sophisticatedbackpacks:crafting_upgrade|true",
		"sophisticatedbackpacks:deposit_upgrade|true",
		"sophisticatedbackpacks:advanced_deposit_upgrade|true",
		"sophisticatedbackpacks:everlasting_upgrade|true",
		"sophisticatedbackpacks:feeding_upgrade|false",
		"sophisticatedbackpacks:advanced_feeding_upgrade|false",
		"sophisticatedbackpacks:filter_upgrade|true",
		"sophisticatedbackpacks:advanced_filter_upgrade|true",
		"sophisticatedbackpacks:inception_upgrade|true",
		"sophisticatedbackpacks:jukebox_upgrade|true",
		"sophisticatedbackpacks:magnet_upgrade|true",
		"sophisticatedbackpacks:advanced_magnet_upgrade|true",
		"sophisticatedbackpacks:pickup_upgrade|true",
		"sophisticatedbackpacks:advanced_pickup_upgrade|true",
		"sophisticatedbackpacks:pump_upgrade|alse",
		"sophisticatedbackpacks:advanced_pump_upgrade|alse",
		"sophisticatedbackpacks:refill_upgrade|true",
		"sophisticatedbackpacks:advanced_refill_upgrade|true",
		"sophisticatedbackpacks:restock_upgrade|true",
		"sophisticatedbackpacks:advanced_restock_upgrade|true",
		"sophisticatedbackpacks:stonecutter_upgrade|true",
		"sophisticatedbackpacks:tank_upgrade|false",
		"sophisticatedbackpacks:tool_swapper_upgrade|false",
		"sophisticatedbackpacks:advanced_tool_swapper_upgrade|false",
		"sophisticatedbackpacks:upgrade_base|true",
		"sophisticatedbackpacks:void_upgrade|true",
		"sophisticatedbackpacks:advanced_void_upgrade|true",
		"sophisticatedbackpacks:xp_pump_upgrade|false",
		
		"sophisticatedbackpacks:blasting_upgrade|false",
		"sophisticatedbackpacks:auto_blasting_upgrade|false",
		"sophisticatedbackpacks:smelting_upgrade|false",
		"sophisticatedbackpacks:auto_smelting_upgrade|false",
		"sophisticatedbackpacks:smoking_upgrade|false",
		"sophisticatedbackpacks:auto_smoking_upgrade|false",

		"sophisticatedbackpacks:backpack|true",
		"sophisticatedbackpacks:copper_backpack|true",
		"sophisticatedbackpacks:iron_backpack|true",
		"sophisticatedbackpacks:gold_backpack|true",
		"sophisticatedbackpacks:diamond_backpack|true",
		"sophisticatedbackpacks:netherite_backpack|true",
		
		"sophisticatedbackpacks:stack_upgrade_tier_1|true",
		"sophisticatedbackpacks:stack_upgrade_starter_tier|true",
		"sophisticatedbackpacks:stack_upgrade_tier_2|true",
		"sophisticatedbackpacks:stack_upgrade_tier_3|true",
		"sophisticatedbackpacks:stack_upgrade_tier_4|true",

		"sophisticatedstorage:controller|true",
		"sophisticatedstorage:debug_tool|true",	
		"sophisticatedstorage:packing_tape|true",
		"sophisticatedstorage:storage_link|true",
		"sophisticatedstorage:storage_tool|true",

		"sophisticatedstorage:compacting_upgrade|true",
		"sophisticatedstorage:advanced_compacting_upgrade|true",
		"sophisticatedstorage:compression_upgrade|true",
		"sophisticatedstorage:crafting_upgrade|false",
		"sophisticatedstorage:feeding_upgrade|false",
		"sophisticatedstorage:advanced_feeding_upgrade|false",
		"sophisticatedstorage:filter_upgrade|true",
		"sophisticatedstorage:advanced_filter_upgrade|true",
		"sophisticatedstorage:hopper_upgrade|true",
		"sophisticatedstorage:advanced_hopper_upgrade|true",
		"sophisticatedstorage:jukebox_upgrade|true",
		"sophisticatedstorage:magnet_upgrade|true",
		"sophisticatedstorage:advanced_magnet_upgrade|true",
		"sophisticatedstorage:pickup_upgrade|true",
		"sophisticatedstorage:advanced_pickup_upgrade|true",
		"sophisticatedstorage:pump_upgrade|false",
		"sophisticatedstorage:advanced_pump_upgrade|false",
		"sophisticatedstorage:stonecutter_upgrade|true",
		"sophisticatedstorage:upgrade_base|true",
		"sophisticatedstorage:void_upgrade|true",
		"sophisticatedstorage:advanced_void_upgrade|true",
		"sophisticatedstorage:xp_pump_upgrade|false",
		
		"sophisticatedstorage:blasting_upgrade|false",
		"sophisticatedstorage:auto_blasting_upgrade|false",
		"sophisticatedstorage:smelting_upgrade|false",
		"sophisticatedstorage:auto_smelting_upgrade|false",
		"sophisticatedstorage:smoking_upgrade|false",
		"sophisticatedstorage:auto_smoking_upgrade|false",

		"sophisticatedstorage:barrel|true",
		"sophisticatedstorage:copper_barrel|false",
		"sophisticatedstorage:iron_barrel|false",		
		"sophisticatedstorage:gold_barrel|false",
		"sophisticatedstorage:diamond_barrel|false",
		"sophisticatedstorage:netherite_barrel|false",

		"sophisticatedstorage:chest|true",
		"sophisticatedstorage:copper_chest|false",
		"sophisticatedstorage:iron_chest|false",
		"sophisticatedstorage:gold_chest|false",
		"sophisticatedstorage:diamond_chest|false",
		"sophisticatedstorage:netherite_chest|false",
		
		"sophisticatedstorage:shulker_box|true",
		"sophisticatedstorage:copper_shulker_box|false",
		"sophisticatedstorage:iron_shulker_box|false",
		"sophisticatedstorage:gold_shulker_box|false",
		"sophisticatedstorage:diamond_shulker_box|false",
		"sophisticatedstorage:netherite_shulker_box|false",
	
		"sophisticatedstorage:limited_barrel_1|false",
		"sophisticatedstorage:limited_copper_barrel_1|false",
		"sophisticatedstorage:limited_iron_barrel_1|false",
		"sophisticatedstorage:limited_gold_barrel_1|false",
		"sophisticatedstorage:limited_diamond_barrel_1|false",
		"sophisticatedstorage:limited_netherite_barrel_1|false",

		"sophisticatedstorage:limited_barrel_2|false",
		"sophisticatedstorage:limited_copper_barrel_2|false",
		"sophisticatedstorage:limited_iron_barrel_2|false",
		"sophisticatedstorage:limited_gold_barrel_2|false",
		"sophisticatedstorage:limited_diamond_barrel_2|false",
		"sophisticatedstorage:limited_netherite_barrel_2|false",

		"sophisticatedstorage:limited_barrel_3|false",
		"sophisticatedstorage:limited_copper_barrel_3|false",
		"sophisticatedstorage:limited_iron_barrel_3|false",
		"sophisticatedstorage:limited_gold_barrel_3|false",
		"sophisticatedstorage:limited_diamond_barrel_3|false",
		"sophisticatedstorage:limited_netherite_barrel_3|false",

		"sophisticatedstorage:limited_barrel_4|false",
		"sophisticatedstorage:limited_copper_barrel_4|false",
		"sophisticatedstorage:limited_iron_barrel_4|false",
		"sophisticatedstorage:limited_gold_barrel_4|false",
		"sophisticatedstorage:limited_diamond_barrel_4|false",
		"sophisticatedstorage:limited_netherite_barrel_4|false",
		
		"sophisticatedstorage:stack_upgrade_tier_1|true",
		"sophisticatedstorage:stack_upgrade_tier_1_plus|true",
		"sophisticatedstorage:stack_upgrade_tier_2|true",
		"sophisticatedstorage:stack_upgrade_tier_3|true",
		"sophisticatedstorage:stack_upgrade_tier_4|true",

		"sophisticatedstorage:basic_tier_upgrade|true",

		"sophisticatedstorage:basic_to_copper_tier_upgrade|true",
		"sophisticatedstorage:basic_to_iron_tier_upgrade|false",
		"sophisticatedstorage:basic_to_gold_tier_upgrade|false",
		"sophisticatedstorage:basic_to_diamond_tier_upgrade|false",
		"sophisticatedstorage:basic_to_netherite_tier_upgrade|false",

		"sophisticatedstorage:copper_to_iron_tier_upgrade|true",
		"sophisticatedstorage:copper_to_gold_tier_upgrade|false",
		"sophisticatedstorage:copper_to_diamond_tier_upgrade|false",
		"sophisticatedstorage:copper_to_netherite_tier_upgrade|false",

		"sophisticatedstorage:iron_to_gold_tier_upgrade|true",
		"sophisticatedstorage:iron_to_diamond_tier_upgrade|false",
		"sophisticatedstorage:iron_to_netherite_tier_upgrade|false",

		"sophisticatedstorage:gold_to_diamond_tier_upgrade|true",
		"sophisticatedstorage:gold_to_netherite_tier_upgrade|false",
		
		"sophisticatedstorage:diamond_to_netherite_tier_upgrade|true"
]

