#Conversion multiplier from Aura to Power
#Range: 4.9E-324 ~ 1.7976931348623157E308
auraConversion = 40.0
#Conversion multiplier from Source to Power
#Range: 4.9E-324 ~ 1.7976931348623157E308
sourceConversion = 200.0

["Dim type"]
	#Power Buffer size  of the Dim type
	#Range: > 0
	powerBuffer = 120000
	#Max amount of power transfer for the Dim type per tick
	#Range: > 0
	maxPowertransfer = 500
	#Range the Dim type can connect to Source containers
	#Range: > 0
	range = 8
	#Ticks to wait for next operation for the DIM type
	#Range: > 0
	tickinterval = 80
	#Amount of Source to convert per Operation with the Dim type
	#Range: > 0
	amountperoperation = 50
	#Amount of Aura to drain/provide when theDim type operates
	#Range: > 0
	change = 750

["Bright type"]
	#Power Buffer size  of the Bright type
	#Range: > 0
	powerBuffer = 480000
	#Max amount of power transfer for the Bright type per tick
	#Range: > 0
	maxPowertransfer = 4000
	#Range the Bright type can connect to Source containers
	#Range: > 0
	range = 8
	#Ticks to wait for next operation for the BRIGHT type
	#Range: > 0
	tickinterval = 40
	#Amount of Source to convert per Operation with the Bright type
	#Range: > 0
	amountperoperation = 50
	#Amount of Aura to drain/provide when theBright type operates
	#Range: > 0
	change = 3750

["Iridescent type"]
	#Power Buffer size  of the Iridescent type
	#Range: > 0
	powerBuffer = 960000
	#Max amount of power transfer for the Iridescent type per tick
	#Range: > 0
	maxPowertransfer = 16000
	#Range the Iridescent type can connect to Source containers
	#Range: > 0
	range = 8
	#Ticks to wait for next operation for the IRIDESCENT type
	#Range: > 0
	tickinterval = 20
	#Amount of Source to convert per Operation with the Iridescent type
	#Range: > 0
	amountperoperation = 50
	#Amount of Aura to drain/provide when theIridescent type operates
	#Range: > 0
	change = 7750

