
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 632239
	#The name of the modpack
	modpackName = "Enigmatica 9"
	#The version of the modpack
	modpackVersion = "1.6.0"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

