
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 882461
	#The name of the modpack
	modpackName = "Enigmatica 9 Expert"
	#The version of the modpack
	modpackVersion = "1.25.0"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

