
#Wires
[wires]
	#Connector max input in FE/t (Energy transfer).
	#Range: > 0
	connector_max_input = 1024
	#Max wire length in blocks.
	#Range: 0 ~ 256
	wire_length = 12
	#Connector max output in FE/t (Energy transfer).
	#Range: > 0
	connector_max_output = 1024
	#Connector internal input buffer in FE.
	#Range: > 0
	connector_input_capacity = 2048
	#Ignore checking if block face can support connector.
	connector_ignore_face_check = false

#Make sure config changes are duplicated on both Clients and the Server when running a dedicated Server,
# as the config isnt synced between Clients and Server.
#General Settings
[general]
	#Forge Energy conversion rate (in FE/t at 256 RPM).
	#Range: > 0
	fe_conversion = 240
	#Max stress for the Alternator and Electric Motor (in SU at 256 RPM).
	#Range: 0 ~ 16383
	baseline_stress = 8192

#Electric Motor
[electric_motor]
	#Electric Motor internal capacity in FE.
	#Range: > 0
	motor_capacity = 2048
	#Electric Motor minimum required energy consumption in FE/t.
	#Range: > 0
	motor_min_consumption = 8
	#Electric Motor max input in FE (Energy transfer not consumption).
	#Range: > 0
	motor_max_input = 256
	#Electric Motor min/max RPM.
	#Range: > 1
	motor_rpm_range = 256

#Heater
[heater]
	#Enable Induction Heater when attached to a Furnace Engine.
	heater_furnace_engine_enable = false
	#Induction Heater internal capacity in FE.
	#Range: > 0
	heater_capacity = 2048
	#Induction Heater max input in FE (Energy transfer, not consumption).
	#Range: > 0
	heater_max_input = 256
	#Induction Heater normal consumption rate in FE/t.
	#Range: > 0
	heater_normal_consumption = 96
	#Induction Heater when attached to a Furnace Engine consumption rate in FE/t.
	#Range: > 0
	heater_furnace_engine_consumption = 1024

#Tesla Coil
[tesla_coil]
	#Tesla Coil charge rate in FE/t.
	#Range: > 0
	tesla_coil_charge_rate = 4096
	#Tesla Coil fire interval (in ticks).
	#Range: > 0
	tesla_coil_fire_cooldown = 20
	#Hurt range (in blocks/meters).
	#Range: > 0
	tesla_coil_hurt_range = 3
	#Charger internal capacity in FE.
	#Range: > 0
	tesla_coil_capacity = 32000
	#Energy consumed when Tesla Coil is fired (in FE).
	#Range: > 0
	tesla_coil_hurt_energy_required = 1024
	#The duration of the Shocked effect for mobs (in ticks).
	#Range: > 0
	tesla_coil_effect_time_mob = 20
	#The duration of the Shocked effect for players (in ticks).
	#Range: > 0
	tesla_coil_effect_time_player = 20
	#Tesla Coil max input in FE/t (Energy transfer).
	#Range: > 0
	tesla_coil_max_input = 8192
	#Tesla Coil charge rate in FE/t for recipes.
	#Range: > 0
	tesla_coil_recipe_charge_rate = 1024
	#Damaged dealt to mobs when Tesla Coil is fired (in half hearts).
	#Range: > 0
	tesla_coil_hurt_mob = 3
	#Damaged dealt to players when Tesla Coil is fired (in half hearts).
	#Range: > 0
	tesla_coil_hurt_player = 2

#Alternator
[alternator]
	#Alternator efficiency relative to base conversion rate.
	#Range: 0.01 ~ 1.0
	generator_efficiency = 0.75
	#Alternator internal capacity in FE.
	#Range: > 0
	generator_capacity = 2048
	#Alternator max input in FE (Energy transfer, not generation).
	#Range: > 0
	generator_max_output = 256

#Accumulator
[accumulator]
	#Accumulator internal capacity in FE.
	#Range: > 0
	accumulator_capacity = 4196000
	#Accumulator max output in FE/t (Energy transfer).
	#Range: > 0
	accumulator_max_output = 512
	#Accumulator max input in FE/t (Energy transfer).
	#Range: > 0
	accumulator_max_input = 512

#Rolling Mill
[rolling_mill]
	#Rolling Mill duration in ticks.
	#Range: > 0
	rolling_mill_processing_duration = 100
	#Rolling Mill base stress impact.
	#Range: 0 ~ 1024
	rolling_mill_stress = 16

#Misc
[misc]
	#Diamond Grit Sandpaper durability (number of uses).
	#Range: > 3
	diamond_grit_sandpaper_uses = 1024

