
[types]

	[types.leaves_type]

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			green_archwood = true
			purple_archwood = true
			red_archwood = true

		[types.leaves_type.twilightforest]
			beanstalk = true
			thorn = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.naturesaura]
			ancient = true
			golden = true

		[types.leaves_type.occultism]
			otherworld = true

		[types.leaves_type.byg]
			araucaria = true
			blue_spruce = true
			blooming_witch_hazel = true
			brown_birch = true
			brown_oak = true
			brown_zelkova = true
			flowering_orchard = true
			flowering_palo_verde = true
			holly_berry = true
			indigo_jacaranda = true
			flowering_jacaranda = true
			flowering_indigo_jacaranda = true
			joshua = true
			ripe_joshua = true
			orange_birch = true
			orange_oak = true
			orange_spruce = true
			orchard = true
			palo_verde = true
			pink_cherry = true
			red_birch = true
			red_maple = true
			red_oak = true
			red_spruce = true
			ripe_orchard = true
			silver_maple = true
			green_apple_skyris = true
			white_cherry = true
			yellow_birch = true
			yellow_spruce = true
			withering_oak = true
			flowering_nightshade = true
			firecracker = true
			aspen = true
			baobab = true
			blue_enchanted = true
			cika = true
			cypress = true
			ebony = true
			ether = true
			fir = true
			green_enchanted = true
			holly = true
			lament = true
			jacaranda = true
			mahogany = true
			white_mangrove = true
			maple = true
			nightshade = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			skyris = true
			willow = true
			witch_hazel = true
			zelkova = true
			flowering_baobab = true
			ripe_baobab = true
			flowering_joshua = true
			flowering_skyris = true

		[types.leaves_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.leaves_type.quark]
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			pink_blossom = true
			yellow_blossom = true
			red_blossom = true
			ancient = true

		[types.leaves_type.ars_elemental]
			yellow_archwood = true

		[types.leaves_type.thermal]
			rubberwood = true

	[types.wood_type]

		[types.wood_type.ars_nouveau]
			archwood = true

		[types.wood_type.quark]
			azalea = true
			blossom = true
			bamboo = true
			ancient = true

		[types.wood_type.naturesaura]
			ancient = true

		[types.wood_type.byg]
			aspen = true
			baobab = true
			blue_enchanted = true
			bulbis = true
			cherry = true
			cika = true
			cypress = true
			ebony = true
			ether = true
			fir = true
			green_enchanted = true
			holly = true
			imparius = true
			lament = true
			jacaranda = true
			mahogany = true
			white_mangrove = true
			maple = true
			nightshade = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			skyris = true
			willow = true
			witch_hazel = true
			zelkova = true
			sythian = true

		[types.wood_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.wood_type.thermal]
			rubberwood = true

	[types.cut_block_type]

		[types.cut_block_type.supplementaries]
			lapis_bricks = true
			ash_bricks = true
			stone_tile = true
			blackstone_tile = true

		[types.cut_block_type.naturesaura]
			ancient = true
			infused_brick = true

		[types.cut_block_type.pneumaticcraft]
			reinforced_brick = true
			reinforced_stone = true
			compressed_brick = true
			compressed_stone = true

		[types.cut_block_type.ae2]
			sky_stone_brick = true
			sky_stone_small_brick = true
			smooth_quartz = true
			quartz_brick = true
			quartz_pillar = true

		[types.cut_block_type.immersiveengineering]
			sheetmetal_copper = true
			sheetmetal_aluminum = true
			storage_aluminum = true
			sheetmetal_lead = true
			storage_lead = true
			sheetmetal_silver = true
			storage_silver = true
			sheetmetal_nickel = true
			storage_nickel = true
			sheetmetal_uranium = true
			storage_uranium = true
			sheetmetal_constantan = true
			storage_constantan = true
			sheetmetal_electrum = true
			storage_electrum = true
			sheetmetal_steel = true
			storage_steel = true
			sheetmetal_iron = true
			sheetmetal_gold = true
			treated_wood_horizontal = true
			treated_wood_vertical = true
			treated_wood_packaged = true
			sheetmetal_colored_white = true
			sheetmetal_colored_orange = true
			sheetmetal_colored_magenta = true
			sheetmetal_colored_light_blue = true
			sheetmetal_colored_yellow = true
			sheetmetal_colored_lime = true
			sheetmetal_colored_pink = true
			sheetmetal_colored_gray = true
			sheetmetal_colored_light_gray = true
			sheetmetal_colored_cyan = true
			sheetmetal_colored_purple = true
			sheetmetal_colored_blue = true
			sheetmetal_colored_brown = true
			sheetmetal_colored_green = true
			sheetmetal_colored_red = true
			sheetmetal_colored_black = true
			steel_scaffolding_standard = true
			alu_scaffolding_standard = true
			steel_scaffolding_grate_top = true
			alu_scaffolding_grate_top = true
			steel_scaffolding_wooden_top = true
			alu_scaffolding_wooden_top = true
			cokebrick = true
			blastbrick = true
			blastbrick_reinforced = true
			coke = true
			hempcrete = true
			concrete = true
			concrete_tile = true
			concrete_leaded = true
			insulating_glass = true
			alloybrick = true
			hempcrete_brick = true
			concrete_brick = true

		[types.cut_block_type.occultism]
			otherstone = true

		[types.cut_block_type.byg]
			cattail_thatch = true
			yellow_nether_brick = true
			blue_nether_brick = true
			purpur_stone = true
			ether_stone = true
			cobbled_ether_stone = true
			carved_ether_stone = true
			chiseled_therium = true
			shiny_chiseled_therium = true
			cryptic_stone = true
			chiseled_fungal_imparius = true
			windswept_sandstone = true
			chiseled_windswept_sandstone = true
			cut_windswept_sandstone = true
			smooth_windswept_sandstone = true
			dacite = true
			dacite_brick = true
			dacite_cobblestone = true
			dacite_tile = true
			red_rock = true
			red_rock_brick = true
			cracked_red_rock_brick = true
			chiseled_red_rock_brick = true
			mossy_red_rock_brick = true
			mossy_stone = true
			rocky_stone = true
			travertine = true
			polished_travertine = true
			chiseled_travertine = true
			scoria_stone = true
			scoria_cobblestone = true
			scoria_stonebrick = true
			soapstone = true
			polished_soapstone = true
			soapstone_brick = true
			soapstone_tile = true
			aspen = true
			baobab = true
			blue_enchanted = true
			bulbis = true
			cherry = true
			cika = true
			cypress = true
			ebony = true
			ether = true
			fir = true
			green_enchanted = true
			holly = true
			imparius = true
			lament = true
			jacaranda = true
			mahogany = true
			white_mangrove = true
			maple = true
			nightshade = true
			palm = true
			pine = true
			rainbow_eucalyptus = true
			redwood = true
			skyris = true
			willow = true
			witch_hazel = true
			zelkova = true
			sythian = true
			embur = true

		[types.cut_block_type.hexerei]
			mahogany = true
			polished_mahogany = true
			willow = true
			polished_willow = true
			witch_hazel = true
			polished_witch_hazel = true

		[types.cut_block_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.cut_block_type.ars_nouveau]
			archwood = true
			sourcestone = true
			sourcestone_mosaic = true
			sourcestone_basketweave = true
			sourcestone_alternating = true
			sourcestone_large_bricks = true
			sourcestone_small_bricks = true
			smooth_sourcestone_basketweave = true
			smooth_sourcestone_mosaic = true
			smooth_sourcestone_alternating = true
			smooth_sourcestone_large_bricks = true
			smooth_sourcestone = true
			smooth_sourcestone_small_bricks = true
			gilded_sourcestone_mosaic = true
			gilded_sourcestone_basketweave = true
			gilded_sourcestone_alternating = true
			gilded_sourcestone_large_bricks = true
			gilded_sourcestone_small_bricks = true
			smooth_gilded_sourcestone_mosaic = true
			smooth_gilded_sourcestone_basketweave = true
			smooth_gilded_sourcestone_alternating = true
			smooth_gilded_sourcestone_large_bricks = true
			smooth_gilded_sourcestone_small_bricks = true

		[types.cut_block_type.simplytools]
			clean_end_stone = true

		[types.cut_block_type.create]
			copper_shingle = true
			exposed_copper_shingle = true
			weathered_copper_shingle = true
			oxidized_copper_shingle = true
			waxed_copper_shingle = true
			waxed_exposed_copper_shingle = true
			waxed_weathered_copper_shingle = true
			waxed_oxidized_copper_shingle = true
			copper_tile = true
			exposed_copper_tile = true
			weathered_copper_tile = true
			oxidized_copper_tile = true
			waxed_copper_tile = true
			waxed_exposed_copper_tile = true
			waxed_weathered_copper_tile = true
			waxed_oxidized_copper_tile = true
			cut_granite = true
			polished_cut_granite = true
			cut_granite_brick = true
			small_granite_brick = true
			cut_diorite = true
			polished_cut_diorite = true
			cut_diorite_brick = true
			small_diorite_brick = true
			cut_andesite = true
			polished_cut_andesite = true
			cut_andesite_brick = true
			small_andesite_brick = true
			cut_calcite = true
			polished_cut_calcite = true
			cut_calcite_brick = true
			small_calcite_brick = true
			cut_dripstone = true
			polished_cut_dripstone = true
			cut_dripstone_brick = true
			small_dripstone_brick = true
			cut_deepslate = true
			polished_cut_deepslate = true
			cut_deepslate_brick = true
			small_deepslate_brick = true
			cut_tuff = true
			polished_cut_tuff = true
			cut_tuff_brick = true
			small_tuff_brick = true
			cut_asurine = true
			polished_cut_asurine = true
			cut_asurine_brick = true
			small_asurine_brick = true
			cut_crimsite = true
			polished_cut_crimsite = true
			cut_crimsite_brick = true
			small_crimsite_brick = true
			cut_limestone = true
			polished_cut_limestone = true
			cut_limestone_brick = true
			small_limestone_brick = true
			cut_ochrum = true
			polished_cut_ochrum = true
			cut_ochrum_brick = true
			small_ochrum_brick = true
			cut_scoria = true
			polished_cut_scoria = true
			cut_scoria_brick = true
			small_scoria_brick = true
			cut_scorchia = true
			polished_cut_scorchia = true
			cut_scorchia_brick = true
			small_scorchia_brick = true
			cut_veridium = true
			polished_cut_veridium = true
			cut_veridium_brick = true
			small_veridium_brick = true

		[types.cut_block_type.quark]
			iron_plate = true
			rusty_iron_plate = true
			blue_nether_bricks = true
			sandstone_bricks = true
			red_sandstone_bricks = true
			soul_sandstone_bricks = true
			cobblestone_bricks = true
			mossy_cobblestone_bricks = true
			blackstone_bricks = true
			dirt_bricks = true
			netherrack_bricks = true
			raw_iron_bricks = true
			raw_gold_bricks = true
			raw_copper_bricks = true
			calcite = true
			polished_calcite = true
			dripstone_block = true
			polished_dripstone = true
			tuff = true
			polished_tuff = true
			granite_bricks = true
			diorite_bricks = true
			andesite_bricks = true
			calcite_bricks = true
			dripstone_bricks = true
			tuff_bricks = true
			limestone_bricks = true
			jasper_bricks = true
			shale_bricks = true
			myalite_bricks = true
			azalea_planks = true
			thatch = true
			soul_sandstone = true
			cut_soul_sandstone = true
			smooth_soul_sandstone = true
			shingles = true
			white_shingles = true
			orange_shingles = true
			magenta_shingles = true
			light_blue_shingles = true
			yellow_shingles = true
			lime_shingles = true
			pink_shingles = true
			gray_shingles = true
			light_gray_shingles = true
			cyan_shingles = true
			purple_shingles = true
			blue_shingles = true
			brown_shingles = true
			green_shingles = true
			red_shingles = true
			black_shingles = true
			midori_block = true
			limestone = true
			polished_limestone = true
			jasper = true
			polished_jasper = true
			shale = true
			polished_shale = true
			myalite = true
			polished_myalite = true
			blossom_planks = true
			duskbound_block = true
			permafrost = true
			permafrost_bricks = true
			ancient_planks = true
			bamboo_planks = true

		[types.cut_block_type.thermal]
			rubberwood = true

[entries]

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

	[entries.wood_type]

		[entries.wood_type.quark]
			vertical_planks = true
			ladder = true
			post = true
			trapped_chest = true
			chest = true
			bookshelf = true
			stripped_post = true
			hollow_log = true

		[entries.wood_type.twilightforest]
			banister = true
			hollow_log_climbable = true
			hollow_log_horizontal = true
			hollow_log_vertical = true

		[entries.wood_type.decorative_blocks]
			seat = true
			palisade = true
			beam = true
			support = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.wood_type.chipped]
			fine_planks = true
			checkered_trapdoor = true
			overgrown_trapdoor = true
			overgrown_door = true
			windowed_door = true
			tiled_door = true
			classic_trapdoor = true
			circle_glass = true
			pegged_planks = true
			torch = true
			secret_door = true
			smooth_planks = true
			screen_door = true
			bared_glass = true
			ornate_bared_glass = true
			hewn_planks = true
			crossed_planks = true
			beach_door = true
			fine_vertical_planks = true
			cross_laced_planks = true
			diamond_bordered_glass = true
			railed_planks = true
			planks_mosaic = true
			distorted_trapdoor = true
			iron_barred_trapdoor = true
			circle_glass_pane = true
			versailles_planks = true
			whirlwind_planks = true
			large_diamond_glass_pane = true
			framed_planks = true
			square_glass = true
			vined_trapdoor = true
			barrel = true
			woven_glass = true
			detailed_planks = true
			woven_trapdoor = true
			cobweb_trapdoor = true
			gated_door = true
			supported_door = true
			barred_trapdoor = true
			line_bared_glass_pane = true
			horizontal_lined_glass_pane = true
			airy_trapdoor = true
			line_bared_glass = true
			slanted_planks = true
			barred_door = true
			suspicious_trapdoor = true
			herringbone_planks = true
			pressed_door = true
			planks_panel = true
			vertically_railed_planks = true
			bared_glass_pane = true
			diamond_bordered_glass_pane = true
			solid_trapdoor = true
			tiled_planks = true
			boarded_door = true
			dual_paneled_door = true
			square_glass_pane = true
			meshed_trapdoor = true
			thin_planks = true
			fancy_trapdoor = true
			paper_door = true
			warted_trapdoor = true
			basket_woven_planks = true
			enclosed_planks = true
			double_herringbone_planks = true
			crated_planks = true
			horizontal_lined_glass = true
			natural_planks = true
			classic_windowed_trapdoor = true
			brick_bond_planks = true
			wickered_planks = true
			bordered_glass_pane = true
			sliding_door = true
			heavy_trapdoor = true
			bordered_glass = true
			laced_planks = true
			boxed_planks = true
			reinforced_crate = true
			large_diamond_glass = true
			snowflake_glass_pane = true
			bricky_planks = true
			slotted_trapdoor = true
			shack_door = true
			polished_planks = true
			ornate_bared_glass_pane = true
			diagonal_planks = true
			wall_torch = true
			crate = true
			nailed_planks = true
			cornered_planks = true
			shifted_planks = true
			vertical_planks = true
			glass_door = true
			fortified_door = true
			paneled_door = true
			leafy_trapdoor = true
			snowflake_glass = true
			heavy_door = true
			pointless_trapdoor = true
			stacked_planks = true
			planks_shavings = true
			twisted_trapdoor = true
			diamond_planks = true
			woven_glass_pane = true
			windowed_trapdoor = true
			tile_windowed_door = true
			golden_barred_trapdoor = true

