
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Allows the mod to try to remap and convert other blocks and items from other compat mods that have been uninstalled from one world. This was made so one can uninstall such mods seamlessly having their blocks converted into Evety Compat counterparts
	remap_other_mods = false
	#Clears out and remaps all blocks registered by this mod belonging to uninstalled wood types to air or oak wood
	remap_self = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	debug_resources = false

