#Use the client implementation even on servers that have the mod installed - only useful for development purposes.
forceClientImplementation = false
#Should ctrl-clicking only move one item at a time instead of the full stack?
enableSingleTransfer = true
#Should shift-ctrl-clicking move all items of the same type at once?
enableBulkTransfer = true
#Should space-clicking an item move all items from that inventory at once?
enableBulkTransferAll = true
#Should shift-ctrl-drop-clicking drop all items of the same type at once?
enableBulkDrop = true
#Should space-clicking move all items even if an empty slot was clicked?
allowBulkTransferAllOnEmptySlot = false
#Should holding shift and moving your mouse over items quick-transfer them without requiring each to be clicked?
enableShiftDrag = true
#Should shift-clicking outside of the screen drop all items of the same type at once?
enableScreenBulkDrop = true

