
#General settings
[general]
	#Cost
	#Range: > -2147483648
	cost = 35
	#The maximum number of times this glyph may appear in a single spell
	#Range: > 1
	per_spell_limit = 2147483647
	#Is Starter Glyph?
	starter = false
	#The tier of the glyph
	#Range: 1 ~ 99
	glyph_tier = 2
	#Is Enabled?
	enabled = true

